// <auto-generated />
using System;
using Archive76.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Archive76.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogueDbContext))]
    partial class CatalogueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Archive76.Domain.Catalogue.CatalogueItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_status");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<int>("ItemKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RetiredUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("retired_utc");

                    b.Property<int>("TrackabilityStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trackability_status");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id");

                    b.ToTable("catalogue_items", (string)null);
                });

            modelBuilder.Entity("Archive76.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id");

                    b.ToTable("players", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
