<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>Archive76.Testing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Archive76.Infrastructure\Archive76.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Archive76.Application\Archive76.Application.csproj" />
    <ProjectReference Include="..\..\src\Archive76.Domain\Archive76.Domain.csproj" />
  </ItemGroup>
</Project>
